name: PenisQueueBukkit
version: ${project.version}
api-version: 1.13
main: PenisQueueBukkit
author: Christallinqq
description: Bukkit companion for PenisQueue
website: https://github.com/christallinqq/penisqueue/
softdepend: [ "ProtocolLib" ]

permissions:
  queue.admin:
    description: Lets you bypass the plugin.
    default: op